package amc.view.staff;

import amc.model.entity.Appointment;
import amc.model.entity.Doctor;
import amc.view.Theme;
import amc.view.comp.AmcRoundBox;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

public class ApptPendingComp extends AmcRoundBox {
    private final Appointment appointment;
    /**
     * Creates new form Processing
     * @param appointment
     */
    public ApptPendingComp(Appointment appointment) {
        initComponents();
        this.appointment = appointment;
        lblApptId.setText(appointment.getId());
        lblDate.setText(appointment.getDateTime().format(DateTimeFormatter.ofPattern("dd MMM yyyy")));
        lblTime.setText(appointment.getDateTime().format(DateTimeFormatter.ofPattern("HH:mm")));
        lblCustomer.setText(appointment.getCustomer().getUserName());
    }

    public void initComboDoc(List<Doctor> docLs) {
        Doctor selected = (Doctor) cmbDoctor.getSelectedItem();
        cmbDoctor.setModel(new DefaultComboBoxModel<> (docLs.toArray(Doctor[]::new)));
        cmbDoctor.setSelectedItem(selected);
    }

    public Doctor getSelectedDoc() { return (Doctor)cmbDoctor.getSelectedItem(); }
    public Appointment getAppointment() { return appointment; }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblApptId = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        picCustomer = new amc.view.comp.AmcPicture();
        picDoctor = new amc.view.comp.AmcPicture();
        lblCustomer = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox<>();
        lblTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnConfirm = new amc.view.comp.AmcButton();
        btnReject = new amc.view.comp.AmcButton();

        setBackground(Theme.C1_INTER);
        set$borderWidth(0);
        set$cornerRound(15);
        setPreferredSize(new java.awt.Dimension(554, 100));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.rowHeights = new int[] {30, 5, 0, 0};
        layout.columnWeights = new double[] {0.5, 0.5};
        layout.rowWeights = new double[] {0.0, 0.0, 0.5, 0.5};
        setLayout(layout);

        lblApptId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblApptId.setForeground(Theme.C1_FG);
        lblApptId.setText("APT-001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(lblApptId, gridBagConstraints);

        lblDate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDate.setForeground(Theme.C1_FG);
        lblDate.setText("27 July 2025");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(lblDate, gridBagConstraints);

        jSeparator1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        add(jSeparator1, gridBagConstraints);

        jPanel1.setOpaque(false);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {30, 0};
        jPanel1Layout.columnWeights = new double[] {0.0, 1.0};
        jPanel1Layout.rowWeights = new double[] {0.5, 0.5};
        jPanel1.setLayout(jPanel1Layout);

        picCustomer.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_patient.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(picCustomer, gridBagConstraints);

        picDoctor.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_doctor.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(picDoctor, gridBagConstraints);

        lblCustomer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblCustomer.setForeground(Theme.C1_FG);
        lblCustomer.setText("Patient Steve");
        lblCustomer.setMaximumSize(new java.awt.Dimension(210, 30));
        lblCustomer.setMinimumSize(new java.awt.Dimension(210, 30));
        lblCustomer.setPreferredSize(new java.awt.Dimension(210, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(lblCustomer, gridBagConstraints);

        cmbDoctor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbDoctor.setMaximumSize(new java.awt.Dimension(210, 30));
        cmbDoctor.setMinimumSize(new java.awt.Dimension(210, 30));
        cmbDoctor.setPreferredSize(new java.awt.Dimension(210, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(cmbDoctor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 0);
        add(jPanel1, gridBagConstraints);

        lblTime.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblTime.setForeground(Theme.C1_FG);
        lblTime.setText("09 : 27 am");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        add(lblTime, gridBagConstraints);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        btnConfirm.setBackground(Theme.DONE_BG);
        btnConfirm.setText("Confirm");
        btnConfirm.set$hoverBackground(Theme.DONE_BG_SELECT);
        btnConfirm.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel3.add(btnConfirm);

        btnReject.setBackground(Theme.WARN_BG);
        btnReject.setText("Reject");
        btnReject.set$hoverBackground(Theme.WARN_BG_SELECT);
        btnReject.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel3.add(btnReject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 10);
        add(jPanel3, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public amc.view.comp.AmcButton btnConfirm;
    public amc.view.comp.AmcButton btnReject;
    private javax.swing.JComboBox<Doctor> cmbDoctor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApptId;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private amc.view.comp.AmcPicture picCustomer;
    private amc.view.comp.AmcPicture picDoctor;
    // End of variables declaration//GEN-END:variables
}
