/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package amc.view.staff;

/**
 *
 * @author kzy
 */
public class BookingPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingPanel
     */
    public BookingPanel() {
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(8);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        processing1 = new amc.view.appointment.Processing();
        processing2 = new amc.view.appointment.Processing();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {0, 50};
        layout.columnWeights = new double[] {0.2, 0.6, 0.2};
        layout.rowWeights = new double[] {1.0, 0.0};
        setLayout(layout);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(true);
        jScrollPane1.setViewportView(null);

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 1000));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWeights = new double[] {1.0};
        jPanel3.setLayout(jPanel3Layout);

        processing1.setMinimumSize(new java.awt.Dimension(0, 100));
        processing1.setPreferredSize(new java.awt.Dimension(0, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(processing1, gridBagConstraints);

        processing2.setMinimumSize(new java.awt.Dimension(0, 100));
        processing2.setPreferredSize(new java.awt.Dimension(0, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(processing2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(filler1, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jButton1.setText("jButton1");
        jButton1.setAlignmentX(1.0F);
        jButton1.setMaximumSize(new java.awt.Dimension(150, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel1.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private amc.view.appointment.Processing processing1;
    private amc.view.appointment.Processing processing2;
    // End of variables declaration//GEN-END:variables
}
