package amc.view.staff;

import amc.view.Theme;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.util.List;

public class BookingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingPanel
     */
    public BookingsPanel() {
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);
    }

    public void renderBookingList(List<ApptPendingComp> bookingLs) {
        bookLsPanel.removeAll();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.gridx  = 0;
        for (ApptPendingComp booking: bookingLs) {
            bookLsPanel.add(booking, gbc);
        }
        bookLsPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        bookLsPanel = new javax.swing.JPanel();
        amcButton1 = new amc.view.comp.AmcButton();

        setBackground(Theme.C1_BG);
        setPreferredSize(new java.awt.Dimension(800, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {0, 50};
        layout.columnWeights = new double[] {0.2, 0.6, 0.2};
        layout.rowWeights = new double[] {1.0, 0.0};
        setLayout(layout);

        jScrollPane1.setBackground(Theme.C1_BG);
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setOpaque(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setViewportView(null);

        bookLsPanel.setBackground(Theme.C1_BG);
        bookLsPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                bookLsPanelAncestorResized(evt);
            }
        });
        java.awt.GridBagLayout jPanel3Layout1 = new java.awt.GridBagLayout();
        jPanel3Layout1.columnWeights = new double[] {1.0};
        bookLsPanel.setLayout(jPanel3Layout1);
        jScrollPane1.setViewportView(bookLsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        amcButton1.setText("Add");
        amcButton1.setAlignmentX(1.0F);
        amcButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        amcButton1.setMaximumSize(new java.awt.Dimension(150, 40));
        amcButton1.setMinimumSize(new java.awt.Dimension(150, 40));
        amcButton1.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(amcButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bookLsPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_bookLsPanelAncestorResized
        // TODO add your handling code here:
        int childHeight = 100;
        for (Component child: bookLsPanel.getComponents()) {
            if (!child.isVisible()) continue;
            childHeight += child.getPreferredSize().height;
        }
        bookLsPanel.setPreferredSize(new Dimension(bookLsPanel.getParent().getWidth(), childHeight));
        bookLsPanel.revalidate();
    }//GEN-LAST:event_bookLsPanelAncestorResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcButton amcButton1;
    private javax.swing.JPanel bookLsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
