package amc.view.staff;

import amc.model.entity.Customer;
import amc.model.entity.Department;
import amc.view.Theme;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class BookingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingPanel
     */
    public BookingsPanel() {
        initComponents();
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);
    }

    public void renderBookingList(List<ApptPendingComp> bookingLs) {
        bookLsPanel.removeAll();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill   = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.CENTER;
        gbc.gridx  = 0;
        for (ApptPendingComp booking: bookingLs) {
            bookLsPanel.add(booking, gbc);
        }
        bookLsPanel.repaint();
    }

    public void openNewBookDialog() {
        switchNewStep("PickCustomer");
        txtNewSearch.setText("");
        cmbNewDept.setSelectedIndex(-1);
        datNewDate.set$date(LocalDate.now());
        fmtNewTime.setText("00:00");
        newBookDialog.pack();
        newBookDialog.setLocationRelativeTo(this);
        newBookDialog.setVisible(true);
    }
    public void closeNewBookDialog() {
        newBookDialog.setVisible(false);
    }

    public String getNewSearchCus() { return txtNewSearch.getText(); }

    public String getNewSelectedCusId() {
        int selectedIndex = tblNewCus.getSelectedRow();
        return (String)tblNewCus.getValueAt(selectedIndex, 0);
    }

    public Department getNewSelectedDept() {
        return (Department)cmbNewDept.getSelectedItem();
    }

    public LocalDateTime getNewSelectedTime() {
        LocalTime time = LocalTime.parse(fmtNewTime.getText(), DateTimeFormatter.ofPattern("HH:mm"));
        return datNewDate.get$date().atTime(time);
    }

    public void renderNewCusLs(List<Customer> customerLs) {
        DefaultTableModel tbModel = (DefaultTableModel) tblNewCus.getModel();
        tbModel.setRowCount(0);
        for (Customer customer: customerLs) {
            tbModel.addRow(new Object[] {
                customer.getId(),
                customer.getUserName(),
                customer.getEmail(),
                customer.getContact(),
                customer.getGender()
            });
        }
    }

    public void renderNewComboDept(List<Department> deptLs) {
        Department selected = (Department)cmbNewDept.getSelectedItem();
        DefaultComboBoxModel<Department> cmbModel = new DefaultComboBoxModel<>();
        cmbModel.addAll(deptLs);
        cmbNewDept.setModel(cmbModel);
        cmbNewDept.setSelectedItem(selected);
    }

    public void switchNewStep(String step) {
        ((CardLayout) newBookCard.getLayout()).show(newBookCard, step);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        newBookDialog = new javax.swing.JDialog();
        lblTitleCreateAppt = new javax.swing.JLabel();
        newBookCard = new javax.swing.JPanel();
        newPickCustomer = new javax.swing.JPanel();
        txtNewSearch = new amc.view.comp.AmcPlaceHolder();
        btnNewSearch = new amc.view.comp.AmcButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNewCus = new javax.swing.JTable();
        newPickDeptTime = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbNewDept = new javax.swing.JComboBox<>();
        datNewDate = new amc.view.comp.AmcDateField();
        fmtNewTime = new javax.swing.JFormattedTextField();
        btnNewBack = new amc.view.comp.AmcButton();
        btnNewNext = new amc.view.comp.AmcButton();
        newPickDoctor = new javax.swing.JPanel();
        newBookComp = new amc.view.staff.ApptPendingComp();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookLsPanel = new javax.swing.JPanel();
        btnNewBook = new amc.view.comp.AmcButton();

        lblTitleCreateAppt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitleCreateAppt.setText("  Create Appointment");
        lblTitleCreateAppt.setPreferredSize(new java.awt.Dimension(100, 35));
        newBookDialog.getContentPane().add(lblTitleCreateAppt, java.awt.BorderLayout.PAGE_START);

        newBookCard.setLayout(new java.awt.CardLayout());

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWeights = new double[] {1.0, 0.0};
        jPanel2Layout.rowWeights = new double[] {0.0, 1.0};
        newPickCustomer.setLayout(jPanel2Layout);

        txtNewSearch.set$hint("IC Num / Name / Email / Contact");
        txtNewSearch.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNewSearch.setMaximumSize(new java.awt.Dimension(100, 30));
        txtNewSearch.setMinimumSize(new java.awt.Dimension(100, 30));
        txtNewSearch.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        newPickCustomer.add(txtNewSearch, gridBagConstraints);

        btnNewSearch.setText("Search");
        btnNewSearch.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnNewSearch.setMaximumSize(new java.awt.Dimension(80, 30));
        btnNewSearch.setMinimumSize(new java.awt.Dimension(80, 30));
        btnNewSearch.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        newPickCustomer.add(btnNewSearch, gridBagConstraints);

        jScrollPane2.setBorder(null);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));

        tblNewCus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IC Num", "Full Name", "Email", "Contact", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblNewCus);
        if (tblNewCus.getColumnModel().getColumnCount() > 0) {
            tblNewCus.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblNewCus.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblNewCus.getColumnModel().getColumn(2).setPreferredWidth(250);
            tblNewCus.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblNewCus.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        newPickCustomer.add(jScrollPane2, gridBagConstraints);

        newBookCard.add(newPickCustomer, "PickCustomer");

        java.awt.GridBagLayout newPickDeptTimeLayout = new java.awt.GridBagLayout();
        newPickDeptTimeLayout.columnWeights = new double[] {0.1, 0.9};
        newPickDeptTimeLayout.rowWeights = new double[] {0.3, 0.3, 0.3, 0.1};
        newPickDeptTime.setLayout(newPickDeptTimeLayout);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Department");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        newPickDeptTime.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Date");
        jLabel2.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        newPickDeptTime.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Time");
        jLabel3.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        newPickDeptTime.add(jLabel3, gridBagConstraints);

        cmbNewDept.setMaximumSize(new java.awt.Dimension(100, 30));
        cmbNewDept.setMinimumSize(new java.awt.Dimension(100, 30));
        cmbNewDept.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        newPickDeptTime.add(cmbNewDept, gridBagConstraints);

        datNewDate.setMaximumSize(new java.awt.Dimension(100, 30));
        datNewDate.setMinimumSize(new java.awt.Dimension(100, 30));
        datNewDate.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        newPickDeptTime.add(datNewDate, gridBagConstraints);

        fmtNewTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        fmtNewTime.setMaximumSize(new java.awt.Dimension(100, 30));
        fmtNewTime.setMinimumSize(new java.awt.Dimension(100, 30));
        fmtNewTime.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        newPickDeptTime.add(fmtNewTime, gridBagConstraints);

        btnNewBack.setBackground(Theme.WARN_BG);
        btnNewBack.setForeground(Theme.C2_FG);
        btnNewBack.setText("< Back");
        btnNewBack.set$hoverBackground(Theme.C2_FG);
        btnNewBack.set$hoverForeground(Theme.C2_FG_SELECT);
        btnNewBack.setMaximumSize(new java.awt.Dimension(80, 30));
        btnNewBack.setMinimumSize(new java.awt.Dimension(80, 30));
        btnNewBack.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        newPickDeptTime.add(btnNewBack, gridBagConstraints);

        btnNewNext.setBackground(Theme.DONE_BG);
        btnNewNext.setForeground(Theme.C2_FG);
        btnNewNext.setText("Next >");
        btnNewNext.set$hoverBackground(Theme.DONE_BG_SELECT);
        btnNewNext.set$hoverForeground(Theme.C2_FG_SELECT);
        btnNewNext.setMaximumSize(new java.awt.Dimension(80, 30));
        btnNewNext.setMinimumSize(new java.awt.Dimension(80, 30));
        btnNewNext.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        newPickDeptTime.add(btnNewNext, gridBagConstraints);

        newBookCard.add(newPickDeptTime, "PickDeptTime");

        newPickDoctor.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        newPickDoctor.add(newBookComp, gridBagConstraints);

        newBookCard.add(newPickDoctor, "PickDoctor");

        newBookDialog.getContentPane().add(newBookCard, java.awt.BorderLayout.CENTER);

        setBackground(Theme.C1_BG);
        setPreferredSize(new java.awt.Dimension(800, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {0, 50};
        layout.columnWeights = new double[] {0.2, 0.6, 0.2};
        layout.rowWeights = new double[] {1.0, 0.0};
        setLayout(layout);

        jScrollPane1.setBackground(Theme.C1_BG);
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setOpaque(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));
        jScrollPane1.setViewportView(null);

        bookLsPanel.setBackground(Theme.C1_BG);
        bookLsPanel.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                bookLsPanelAncestorResized(evt);
            }
        });
        java.awt.GridBagLayout jPanel3Layout1 = new java.awt.GridBagLayout();
        jPanel3Layout1.columnWeights = new double[] {1.0};
        bookLsPanel.setLayout(jPanel3Layout1);
        jScrollPane1.setViewportView(bookLsPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        btnNewBook.setText("Add");
        btnNewBook.setAlignmentX(1.0F);
        btnNewBook.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNewBook.setMaximumSize(new java.awt.Dimension(150, 40));
        btnNewBook.setMinimumSize(new java.awt.Dimension(150, 40));
        btnNewBook.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(btnNewBook, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void bookLsPanelAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_bookLsPanelAncestorResized
        // TODO add your handling code here:
        int childHeight = 100;
        for (Component child: bookLsPanel.getComponents()) {
            if (!child.isVisible()) continue;
            childHeight += child.getPreferredSize().height;
        }
        bookLsPanel.setPreferredSize(new Dimension(bookLsPanel.getParent().getWidth(), childHeight));
        bookLsPanel.revalidate();
    }//GEN-LAST:event_bookLsPanelAncestorResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookLsPanel;
    public amc.view.comp.AmcButton btnNewBack;
    public amc.view.comp.AmcButton btnNewBook;
    public amc.view.comp.AmcButton btnNewNext;
    public amc.view.comp.AmcButton btnNewSearch;
    private javax.swing.JComboBox<Department> cmbNewDept;
    private amc.view.comp.AmcDateField datNewDate;
    private javax.swing.JFormattedTextField fmtNewTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitleCreateAppt;
    private javax.swing.JPanel newBookCard;
    public amc.view.staff.ApptPendingComp newBookComp;
    private javax.swing.JDialog newBookDialog;
    private javax.swing.JPanel newPickCustomer;
    private javax.swing.JPanel newPickDeptTime;
    private javax.swing.JPanel newPickDoctor;
    public javax.swing.JTable tblNewCus;
    private amc.view.comp.AmcPlaceHolder txtNewSearch;
    // End of variables declaration//GEN-END:variables
}
