package amc.view.staff;

import amc.model.entity.Customer;
import amc.view.Theme;
import java.awt.Cursor;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class CustomersPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommentLsPanel
     */
    public CustomersPanel() {
        initComponents();
        this.picSearch.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public String getSearchContent() { return txtSearch.getText(); }

    public void renderCustomerLs(List<Customer> customerLs) {
        DefaultTableModel tbModel = (DefaultTableModel) tblCustomer.getModel();
        tbModel.setRowCount(0);
        for (Customer customer: customerLs) {
            tbModel.addRow(new Object[] {
                customer.getId(),
                customer.getUserName(),
                customer.getEmail(),
                customer.getContact(),
                customer.getGender()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        amcRoundBox1 = new amc.view.comp.AmcRoundBox();
        picSearch = new amc.view.comp.AmcPicture();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new amc.view.comp.AmcButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setBackground(Theme.C1_BG);
        setPreferredSize(new java.awt.Dimension(800, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {50, 0};
        layout.columnWeights = new double[] {0.2, 0.6, 0.2};
        layout.rowWeights = new double[] {0.0, 1.0};
        setLayout(layout);

        jPanel1.setMaximumSize(new java.awt.Dimension(100, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 40));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 40};
        jPanel1Layout.columnWeights = new double[] {1.0, 0.0};
        jPanel1Layout.rowWeights = new double[] {1.0};
        jPanel1.setLayout(jPanel1Layout);

        amcRoundBox1.setBackground(Theme.C1_BG);
        amcRoundBox1.set$borderColor(Theme.C1_FG);
        amcRoundBox1.set$cornerRound(15);
        amcRoundBox1.setMaximumSize(new java.awt.Dimension(100, 36));
        amcRoundBox1.setMinimumSize(new java.awt.Dimension(100, 36));
        amcRoundBox1.setName(""); // NOI18N
        amcRoundBox1.setPreferredSize(new java.awt.Dimension(100, 36));
        java.awt.GridBagLayout amcRoundBox1Layout = new java.awt.GridBagLayout();
        amcRoundBox1Layout.columnWidths = new int[] {37, 0};
        amcRoundBox1Layout.columnWeights = new double[] {0.0, 1.0};
        amcRoundBox1Layout.rowWeights = new double[] {1.0};
        amcRoundBox1.setLayout(amcRoundBox1Layout);

        picSearch.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/icon_search.png"))); // NOI18N
        picSearch.set$maxSize(new java.awt.Dimension(20, 20));
        picSearch.setMaximumSize(new java.awt.Dimension(32, 32));
        picSearch.setMinimumSize(new java.awt.Dimension(32, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 0);
        amcRoundBox1.add(picSearch, gridBagConstraints);

        txtSearch.setBackground(Theme.C1_BG);
        txtSearch.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.setMaximumSize(new java.awt.Dimension(180, 35));
        txtSearch.setMinimumSize(new java.awt.Dimension(180, 35));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 5);
        amcRoundBox1.add(txtSearch, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(amcRoundBox1, gridBagConstraints);

        btnAdd.setText("Add");
        btnAdd.setAlignmentX(1.0F);
        btnAdd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAdd.setMaximumSize(new java.awt.Dimension(120, 40));
        btnAdd.setMinimumSize(new java.awt.Dimension(120, 40));
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel1.add(btnAdd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jPanel1, gridBagConstraints);

        jScrollPane2.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IC Number", "Full Name", "Email", "Contact", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblCustomer.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblCustomer.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblCustomer.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblCustomer.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcRoundBox amcRoundBox1;
    public amc.view.comp.AmcButton btnAdd;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public amc.view.comp.AmcPicture picSearch;
    public javax.swing.JTable tblCustomer;
    public javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
