package amc.view.staff;

import amc.model.entity.Appointment;
import amc.model.entity.Department;
import amc.view.Theme;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class PayingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayLsPanel
     */
    public PayingsPanel() {
        initComponents();
    }

    public void renderComboDept(List<Department> deptLs) {
        Department selected = (Department)cmbDept.getSelectedItem();
        DefaultComboBoxModel<Department> cmbModel = new DefaultComboBoxModel<>();
        cmbModel.addAll(deptLs);
        cmbModel.addAll(0, List.of(new Department("", "#ALL")));
        cmbDept.setModel(cmbModel);
        cmbDept.setSelectedItem(selected);
    }

    public void renderPayAppt(List<Appointment> apptLs) {
        DefaultTableModel tbModel = (DefaultTableModel)tblPayAppt.getModel();
        tbModel.setRowCount(0);
        for (Appointment appt: apptLs) {
            tbModel.addRow(new Object[] {
                appt.getId(),
                appt.getCustomer().getUserName(),
                appt.getCustomer().getEmail(),
                appt.getDepartment().getDepartmentName(),
                appt.getDateTime().format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm"))
            });
        }
    }

    public String getSearchApptId() { return txtApptId.getText(); }

    public String getSearchCusInfo() { return txtCusInfo.getText(); }

    public String getSearchDepartment() {
        if (cmbDept.getSelectedItem() == null) return "";
        return ((Department) cmbDept.getSelectedItem()).getId();
    }

    public void resetSearch() {
        txtApptId.setText("");
        txtCusInfo.setText("");
        cmbDept.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtApptId = new amc.view.comp.AmcPlaceHolder();
        txtCusInfo = new amc.view.comp.AmcPlaceHolder();
        btnSearch = new amc.view.comp.AmcButton();
        cmbDept = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayAppt = new javax.swing.JTable();

        setBackground(Theme.C1_BG);
        setPreferredSize(new java.awt.Dimension(800, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {10, 200, 10};
        layout.rowHeights = new int[] {0, 0};
        layout.columnWeights = new double[] {0.2, 0.6, 0.2};
        layout.rowWeights = new double[] {0.0, 1.0};
        setLayout(layout);

        jPanel1.setOpaque(false);
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 120};
        jPanel1Layout.rowHeights = new int[] {30, 30, 30};
        jPanel1Layout.columnWeights = new double[] {1.0, 0.0};
        jPanel1Layout.rowWeights = new double[] {0.0, 0.0, 0.0};
        jPanel1.setLayout(jPanel1Layout);

        txtApptId.set$hint("Appointment ID");
        txtApptId.setMaximumSize(new java.awt.Dimension(100, 30));
        txtApptId.setMinimumSize(new java.awt.Dimension(100, 30));
        txtApptId.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtApptId, gridBagConstraints);

        txtCusInfo.set$hint("Customer Name/Email/ID");
        txtCusInfo.setMaximumSize(new java.awt.Dimension(100, 30));
        txtCusInfo.setMinimumSize(new java.awt.Dimension(100, 30));
        txtCusInfo.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(txtCusInfo, gridBagConstraints);

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnSearch, gridBagConstraints);

        cmbDept.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbDept.setForeground(Theme.C1_FG);
        cmbDept.setMaximumSize(new java.awt.Dimension(100, 30));
        cmbDept.setMinimumSize(new java.awt.Dimension(100, 30));
        cmbDept.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(cmbDept, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jPanel1, gridBagConstraints);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(100, 100));

        tblPayAppt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appt ID", "Patient", "Email", "Department", "DateTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPayAppt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tblPayAppt);
        if (tblPayAppt.getColumnModel().getColumnCount() > 0) {
            tblPayAppt.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPayAppt.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblPayAppt.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblPayAppt.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblPayAppt.getColumnModel().getColumn(4).setPreferredWidth(160);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 0);
        add(jScrollPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public amc.view.comp.AmcButton btnSearch;
    private javax.swing.JComboBox<Department> cmbDept;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblPayAppt;
    private amc.view.comp.AmcPlaceHolder txtApptId;
    private amc.view.comp.AmcPlaceHolder txtCusInfo;
    // End of variables declaration//GEN-END:variables
}
