/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package amc.view.staff;

import java.awt.CardLayout;

/**
 *
 * @author kzy
 */
public class StaffPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        ((CardLayout) this.getLayout()).show(this, "Booking");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payLsPanel2 = new amc.view.staff.PayLsPanel();
        customerLsPanel2 = new amc.view.staff.CustomerLsPanel();
        bookingPanel2 = new amc.view.staff.BookingPanel();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.CardLayout());
        add(payLsPanel2, "PayLs");
        add(customerLsPanel2, "CustomerLs");
        add(bookingPanel2, "Booking");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.staff.BookingPanel bookingPanel2;
    private amc.view.staff.CustomerLsPanel customerLsPanel2;
    private amc.view.staff.PayLsPanel payLsPanel2;
    // End of variables declaration//GEN-END:variables
}
