package amc.view.share;

import java.awt.Dimension;
import amc.view.Theme;
import java.awt.CardLayout;

public class AppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentPanel
     */
    public AppointmentPanel() {
        initComponents();
        ((CardLayout) jPanel9.getLayout()).show(jPanel9, "Medicine");
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amcPicture1 = new amc.view.comp.AmcPicture();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        amcPicture2 = new amc.view.comp.AmcPicture();
        amcPicture3 = new amc.view.comp.AmcPicture();
        amcPicture4 = new amc.view.comp.AmcPicture();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        amcButton2 = new amc.view.comp.AmcButton();
        amcButton3 = new amc.view.comp.AmcButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        amcButton1 = new amc.view.comp.AmcButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        amcButton4 = new amc.view.comp.AmcButton();
        amcButton5 = new amc.view.comp.AmcButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        amcRoundBox1 = new amc.view.comp.AmcRoundBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        amcPicture5 = new amc.view.comp.AmcPicture();
        amcButton6 = new amc.view.comp.AmcButton();
        amcPicture6 = new amc.view.comp.AmcPicture();
        amcButton7 = new amc.view.comp.AmcButton();
        amcPicture7 = new amc.view.comp.AmcPicture();
        amcButton8 = new amc.view.comp.AmcButton();

        setBackground(Theme.C1_BG);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(Theme.C1_BG);
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 2000));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 2000));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 2000));
        jPanel1.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jPanel1AncestorResized(evt);
            }
        });
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {50, 200, 50};
        jPanel1Layout.rowHeights = new int[] {0, 0, 0, 0, 0};
        jPanel1Layout.columnWeights = new double[] {0.15, 0.7, 0.15};
        jPanel1Layout.rowWeights = new double[] {0.0, 0.0, 0.0, 0.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setOpaque(false);
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.rowHeights = new int[] {40, 30, 5, 35, 35, 35};
        jPanel2Layout.columnWeights = new double[] {0.5, 0.5};
        jPanel2Layout.rowWeights = new double[] {0.0, 0.0, 0.0, 1.0, 1.0, 1.0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(Theme.C1_FG);
        jLabel1.setText("Appointment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel2.setForeground(Theme.C1_FG);
        jLabel2.setText("APT-001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel3.setForeground(Theme.C1_FG);
        jLabel3.setText("13 July 2025");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel3, gridBagConstraints);

        amcPicture1.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/status_pending_30.png"))); // NOI18N
        amcPicture1.setMaximumSize(new java.awt.Dimension(35, 35));
        amcPicture1.setMinimumSize(new java.awt.Dimension(35, 35));
        amcPicture1.setPreferredSize(new java.awt.Dimension(36, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(amcPicture1, gridBagConstraints);

        jSeparator1.setToolTipText("");
        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 3));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jSeparator1, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setForeground(Theme.C1_FG);
        jLabel4.setText("07:04 pm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel2.add(jLabel4, gridBagConstraints);

        amcPicture2.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_patient_30.png"))); // NOI18N
        amcPicture2.setMaximumSize(new java.awt.Dimension(30, 30));
        amcPicture2.setMinimumSize(new java.awt.Dimension(30, 30));
        amcPicture2.setPreferredSize(new java.awt.Dimension(31, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(amcPicture2, gridBagConstraints);

        amcPicture3.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_staff_30.png"))); // NOI18N
        amcPicture3.setMaximumSize(new java.awt.Dimension(30, 30));
        amcPicture3.setMinimumSize(new java.awt.Dimension(30, 30));
        amcPicture3.setPreferredSize(new java.awt.Dimension(31, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(amcPicture3, gridBagConstraints);

        amcPicture4.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_doctor_30.png"))); // NOI18N
        amcPicture4.setMaximumSize(new java.awt.Dimension(30, 30));
        amcPicture4.setMinimumSize(new java.awt.Dimension(30, 30));
        amcPicture4.setPreferredSize(new java.awt.Dimension(31, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(amcPicture4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(Theme.C1_FG);
        jLabel5.setText("Patient Steve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setForeground(Theme.C1_FG);
        jLabel6.setText("Staff Ting Yong");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setForeground(Theme.C1_FG);
        jLabel7.setText("Doctor Yong Heng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setOpaque(false);
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {300, 300};
        jPanel3Layout.rowHeights = new int[] {40, 30, 200, 35};
        jPanel3Layout.columnWeights = new double[] {0.6, 0.4};
        jPanel3.setLayout(jPanel3Layout);

        jLabel8.setBackground(Theme.C1_FG);
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setText("Consultation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(jLabel8, gridBagConstraints);

        jPanel4.setMaximumSize(new java.awt.Dimension(200, 30));
        jPanel4.setMinimumSize(new java.awt.Dimension(200, 30));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        amcButton2.setText("Services");
        amcButton2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel4.add(amcButton2);

        amcButton3.setText("Medicines");
        amcButton3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel4.add(amcButton3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel3.add(jPanel4, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setForeground(Theme.C1_FG);
        jLabel9.setText("Doctor's Feedback");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jLabel9, gridBagConstraints);

        jPanel5.setBorder(new javax.swing.border.LineBorder(Theme.C2_INTER, 2, true));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.CardLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setColumnHeaderView(null);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 100));

        jTable1.setBackground(Theme.C1_BG);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null,  new Boolean(false)},
                {null, null}
            },
            new String [] {
                "Service", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(Theme.C1_INTER);
        jTable1.setRowHeight(25);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(40);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        jPanel5.add(jScrollPane3, "Service");

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setColumnHeaderView(null);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane4.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(100, 100));

        jTable2.setBackground(Theme.C1_BG);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicine", "Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(Theme.C1_INTER);
        jTable2.setRowHeight(25);
        jTable2.setRowSelectionAllowed(false);
        jTable2.setShowGrid(false);
        jTable2.setShowHorizontalLines(true);
        jTable2.setUpdateSelectionOnSort(false);
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(1).setMinWidth(40);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(1).setMaxWidth(40);
        }

        jPanel5.add(jScrollPane4, "Medicine");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel3.add(jPanel5, gridBagConstraints);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(Theme.C2_INTER, 2, true));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(100, 100));

        jTextArea1.setBackground(Theme.C1_BG);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextArea1.setForeground(Theme.C1_FG);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        amcButton1.setText("End Consultation");
        amcButton1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        amcButton1.setMaximumSize(new java.awt.Dimension(150, 30));
        amcButton1.setMinimumSize(new java.awt.Dimension(150, 30));
        amcButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel3.add(amcButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel7.setOpaque(false);
        java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
        jPanel7Layout.columnWidths = new int[] {300, 300};
        jPanel7Layout.rowHeights = new int[] {40, 30, 200, 35};
        jPanel7Layout.columnWeights = new double[] {0.6, 0.4};
        jPanel7.setLayout(jPanel7Layout);

        jLabel10.setBackground(Theme.C1_FG);
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setText("Consultation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel7.add(jLabel10, gridBagConstraints);

        jPanel8.setMaximumSize(new java.awt.Dimension(200, 30));
        jPanel8.setMinimumSize(new java.awt.Dimension(200, 30));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        amcButton4.setText("Services");
        amcButton4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel8.add(amcButton4);

        amcButton5.setText("Medicines");
        amcButton5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPanel8.add(amcButton5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel7.add(jPanel8, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel11.setForeground(Theme.C1_FG);
        jLabel11.setText("Doctor's Feedback");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel7.add(jLabel11, gridBagConstraints);

        jPanel9.setBorder(new javax.swing.border.LineBorder(Theme.C2_INTER, 2, true));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.CardLayout());

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setColumnHeaderView(null);
        jScrollPane5.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane5.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(100, 100));

        jTable3.setBackground(Theme.C1_BG);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null}
            },
            new String [] {
                "Service", "Fee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(Theme.C1_INTER);
        jTable3.setRowHeight(25);
        jTable3.setRowSelectionAllowed(false);
        jTable3.setShowGrid(false);
        jTable3.setShowHorizontalLines(true);
        jTable3.setUpdateSelectionOnSort(false);
        jScrollPane5.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setMinWidth(150);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        jPanel9.add(jScrollPane5, "Service");

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane6.setColumnHeaderView(null);
        jScrollPane6.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane6.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane6.setPreferredSize(new java.awt.Dimension(100, 100));

        jTable4.setBackground(Theme.C1_BG);
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Medicine", "Count", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setGridColor(Theme.C1_INTER);
        jTable4.setRowHeight(25);
        jTable4.setRowSelectionAllowed(false);
        jTable4.setShowGrid(false);
        jTable4.setShowHorizontalLines(true);
        jTable4.setUpdateSelectionOnSort(false);
        jScrollPane6.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(1).setMinWidth(40);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable4.getColumnModel().getColumn(1).setMaxWidth(40);
            jTable4.getColumnModel().getColumn(2).setMinWidth(150);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTable4.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jPanel9.add(jScrollPane6, "Medicine");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel7.add(jPanel9, gridBagConstraints);

        jScrollPane7.setBorder(new javax.swing.border.LineBorder(Theme.C2_INTER, 2, true));
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane7.setMaximumSize(new java.awt.Dimension(100, 100));
        jScrollPane7.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane7.setPreferredSize(new java.awt.Dimension(100, 100));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(Theme.C1_BG);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextArea2.setForeground(Theme.C1_FG);
        jTextArea2.setLineWrap(true);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jScrollPane7.setViewportView(jTextArea2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel7.add(jScrollPane7, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(Theme.C1_FG);
        jLabel12.setText("Total Fees :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel7.add(jLabel12, gridBagConstraints);

        amcRoundBox1.setBackground(Theme.C1_INTER);
        amcRoundBox1.set$borderColor(Theme.C1_FG_DISABLE);
        amcRoundBox1.set$cornerRound(15);
        amcRoundBox1.setMaximumSize(new java.awt.Dimension(250, 28));
        amcRoundBox1.setMinimumSize(new java.awt.Dimension(250, 28));
        amcRoundBox1.setPreferredSize(new java.awt.Dimension(250, 28));
        java.awt.GridBagLayout amcRoundBox1Layout = new java.awt.GridBagLayout();
        amcRoundBox1Layout.columnWeights = new double[] {0.0, 1.0};
        amcRoundBox1.setLayout(amcRoundBox1Layout);

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setForeground(Theme.C1_FG);
        jLabel13.setText("RM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        amcRoundBox1.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel14.setForeground(Theme.C1_FG);
        jLabel14.setText("123.45");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        amcRoundBox1.add(jLabel14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 0, 0);
        jPanel7.add(amcRoundBox1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jPanel7, gridBagConstraints);

        jPanel6.setMaximumSize(new java.awt.Dimension(600, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(600, 100));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(600, 100));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.columnWeights = new double[] {1.0, 1.0, 1.0, 1.0, 1.0, 1.0};
        jPanel6Layout.rowWeights = new double[] {1.0};
        jPanel6.setLayout(jPanel6Layout);

        amcPicture5.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/pay_cash.png"))); // NOI18N
        amcPicture5.set$maxSize(new java.awt.Dimension(150, 100));
        amcPicture5.setMaximumSize(new java.awt.Dimension(100, 50));
        amcPicture5.setMinimumSize(new java.awt.Dimension(100, 50));
        amcPicture5.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(amcPicture5, gridBagConstraints);

        amcButton6.setText("Cash");
        amcButton6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        amcButton6.setMaximumSize(new java.awt.Dimension(100, 60));
        amcButton6.setMinimumSize(new java.awt.Dimension(100, 60));
        amcButton6.setPreferredSize(new java.awt.Dimension(100, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel6.add(amcButton6, gridBagConstraints);

        amcPicture6.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/pay_card.png"))); // NOI18N
        amcPicture6.set$maxSize(new java.awt.Dimension(150, 100));
        amcPicture6.setMaximumSize(new java.awt.Dimension(100, 50));
        amcPicture6.setMinimumSize(new java.awt.Dimension(100, 50));
        amcPicture6.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(amcPicture6, gridBagConstraints);

        amcButton7.setText("Credit/Debit");
        amcButton7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        amcButton7.setMaximumSize(new java.awt.Dimension(100, 60));
        amcButton7.setMinimumSize(new java.awt.Dimension(100, 60));
        amcButton7.setPreferredSize(new java.awt.Dimension(100, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel6.add(amcButton7, gridBagConstraints);

        amcPicture7.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/pay_ewallet.png"))); // NOI18N
        amcPicture7.set$maxSize(new java.awt.Dimension(150, 100));
        amcPicture7.setMaximumSize(new java.awt.Dimension(100, 50));
        amcPicture7.setMinimumSize(new java.awt.Dimension(100, 50));
        amcPicture7.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel6.add(amcPicture7, gridBagConstraints);

        amcButton8.setText("E-Wallet");
        amcButton8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        amcButton8.setMaximumSize(new java.awt.Dimension(100, 60));
        amcButton8.setMinimumSize(new java.awt.Dimension(100, 60));
        amcButton8.setPreferredSize(new java.awt.Dimension(100, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel6.add(amcButton8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(jPanel6, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel1AncestorResized
        // TODO add your handling code here:
        jPanel1.setPreferredSize(new Dimension(jPanel1.getParent().getWidth(), 2000));
        jPanel1.revalidate();
    }//GEN-LAST:event_jPanel1AncestorResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcButton amcButton1;
    private amc.view.comp.AmcButton amcButton2;
    private amc.view.comp.AmcButton amcButton3;
    private amc.view.comp.AmcButton amcButton4;
    private amc.view.comp.AmcButton amcButton5;
    private amc.view.comp.AmcButton amcButton6;
    private amc.view.comp.AmcButton amcButton7;
    private amc.view.comp.AmcButton amcButton8;
    private amc.view.comp.AmcPicture amcPicture1;
    private amc.view.comp.AmcPicture amcPicture2;
    private amc.view.comp.AmcPicture amcPicture3;
    private amc.view.comp.AmcPicture amcPicture4;
    private amc.view.comp.AmcPicture amcPicture5;
    private amc.view.comp.AmcPicture amcPicture6;
    private amc.view.comp.AmcPicture amcPicture7;
    private amc.view.comp.AmcRoundBox amcRoundBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
