package amc.view.share;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.Box;

public class BarPanel extends javax.swing.JPanel {

    /**
     * Creates new form BarPanel
     * @param buttons
     */
    public BarPanel(BarButton... buttons) {
        initComponents();

        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.BOTH;
        for (BarButton btn: buttons) {
            this.add(btn, gbc);
        }

        gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1;
        this.add(new Box.Filler(
            new Dimension(0, 0),
            new Dimension(0, 0),
            new Dimension(32767, 0)
        ), gbc);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.rowWeights = new double[] {1.0};
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
