package amc.view.share;

import amc.view.Theme;

public class EditProfileDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditProfileDialog.class.getName());

    /**
     * Creates new form EditProfileDialog
     */
    public EditProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblTitleEdit = new javax.swing.JLabel();
        editForm = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new amc.view.comp.AmcPlaceHolder();
        lblDateOfBirth = new javax.swing.JLabel();
        amcDateField1 = new amc.view.comp.AmcDateField();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new amc.view.comp.AmcPlaceHolder();
        lblContact = new javax.swing.JLabel();
        txtContact = new amc.view.comp.AmcPlaceHolder();
        lblDepartment = new javax.swing.JLabel();
        amcPlaceHolder6 = new amc.view.comp.AmcPlaceHolder();
        lblLicense = new javax.swing.JLabel();
        txtLicense = new amc.view.comp.AmcPlaceHolder();
        btnConfirm = new amc.view.comp.AmcButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Profile");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(600, 450));

        jPanel1.setBackground(Theme.C2_BG);
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 200));
        java.awt.GridBagLayout jPanel1Layout1 = new java.awt.GridBagLayout();
        jPanel1Layout1.columnWidths = new int[] {10, 200, 10};
        jPanel1Layout1.columnWeights = new double[] {0.2, 0.6, 0.2};
        jPanel1Layout1.rowWeights = new double[] {0.1, 0.8, 0.1};
        jPanel1.setLayout(jPanel1Layout1);

        lblTitleEdit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitleEdit.setForeground(Theme.C2_FG);
        lblTitleEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleEdit.setText("Edit Profile");
        lblTitleEdit.setMaximumSize(new java.awt.Dimension(150, 40));
        lblTitleEdit.setMinimumSize(new java.awt.Dimension(150, 40));
        lblTitleEdit.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(lblTitleEdit, gridBagConstraints);

        editForm.setMaximumSize(new java.awt.Dimension(200, 200));
        editForm.setMinimumSize(new java.awt.Dimension(200, 200));
        editForm.setName(""); // NOI18N
        editForm.setOpaque(false);
        editForm.setPreferredSize(new java.awt.Dimension(200, 200));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {80, 120};
        jPanel1Layout.columnWeights = new double[] {0.2, 0.8};
        editForm.setLayout(jPanel1Layout);

        lblUserName.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblUserName.setText("Full Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblUserName, gridBagConstraints);

        txtUserName.set$hint("@: Tan Nai-Long / Rachael");
        txtUserName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(txtUserName, gridBagConstraints);

        lblDateOfBirth.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblDateOfBirth.setText("Date of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblDateOfBirth, gridBagConstraints);

        amcDateField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(amcDateField1, gridBagConstraints);

        lblGender.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblGender.setText("Gender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblGender, gridBagConstraints);

        cmbGender.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbGender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(cmbGender, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblEmail.setText("Email Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblEmail, gridBagConstraints);

        txtEmail.set$hint("@: xxx@gmail.com");
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(txtEmail, gridBagConstraints);

        lblContact.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblContact.setText("Contact Num");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblContact, gridBagConstraints);

        txtContact.set$hint("@: 0123456789 / +60123456789");
        txtContact.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(txtContact, gridBagConstraints);

        lblDepartment.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblDepartment, gridBagConstraints);

        amcPlaceHolder6.setText("amcPlaceHolder6");
        amcPlaceHolder6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(amcPlaceHolder6, gridBagConstraints);

        lblLicense.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblLicense.setText("Medical License");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        editForm.add(lblLicense, gridBagConstraints);

        txtLicense.set$hint("@: MMC 27000");
        txtLicense.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        editForm.add(txtLicense, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(editForm, gridBagConstraints);

        btnConfirm.setBackground(Theme.C1_BG);
        btnConfirm.setForeground(Theme.C1_FG);
        btnConfirm.setText("Confirm Edit");
        btnConfirm.set$hoverBackground(Theme.C1_BG_SELECT);
        btnConfirm.set$hoverForeground(Theme.C1_FG_SELECT);
        btnConfirm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnConfirm.setMaximumSize(new java.awt.Dimension(120, 30));
        btnConfirm.setMinimumSize(new java.awt.Dimension(120, 30));
        btnConfirm.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(btnConfirm, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditProfileDialog dialog = new EditProfileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcDateField amcDateField1;
    private amc.view.comp.AmcPlaceHolder amcPlaceHolder6;
    private amc.view.comp.AmcButton btnConfirm;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JPanel editForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblTitleEdit;
    private javax.swing.JLabel lblUserName;
    private amc.view.comp.AmcPlaceHolder txtContact;
    private amc.view.comp.AmcPlaceHolder txtEmail;
    private amc.view.comp.AmcPlaceHolder txtLicense;
    private amc.view.comp.AmcPlaceHolder txtUserName;
    // End of variables declaration//GEN-END:variables
}
