package amc.view.share;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import amc.view.Theme;

public class HomePanel extends javax.swing.JPanel {
    private boolean picResizing = false;

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        this.jScrollPane1.setBorder(null);
        this.jScrollPane1.getVerticalScrollBar().setUnitIncrement(12);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        amcPicture1 = new amc.view.comp.AmcPicture();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewport(null);
        jScrollPane1.setViewportView(null);

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.rowHeights = new int[] {0, 0};
        jPanel1Layout.columnWeights = new double[] {1.0};
        jPanel1Layout.rowWeights = new double[] {0.0, 1.0};
        jPanel1.setLayout(jPanel1Layout);

        jLayeredPane1.setForeground(Theme.C2_FG);
        java.awt.GridBagLayout jLayeredPane1Layout = new java.awt.GridBagLayout();
        jLayeredPane1Layout.columnWeights = new double[] {0.15, 0.85};
        jLayeredPane1Layout.rowWeights = new double[] {0.75, 0.0, 0.25};
        jLayeredPane1.setLayout(jLayeredPane1Layout);

        amcPicture1.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/bg_technique.png"))); // NOI18N
        amcPicture1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                amcPicture1ComponentResized(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jLayeredPane1.add(amcPicture1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("<html>\nAPU Medical<br>\nCentre");
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jLayeredPane1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("<html>\n- 100% Survive Rate<br>\n- 100% Trustability");
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jLayeredPane1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jLayeredPane1, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void amcPicture1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_amcPicture1ComponentResized
        // TODO add your handling code here:
        if (this.picResizing) return;
        Image img = ((ImageIcon)this.amcPicture1.get$image()).getImage();
        double scale = (double) img.getHeight(null) / img.getWidth(null);
        int parentW = this.amcPicture1.getParent().getWidth();

        this.picResizing = true;
        this.amcPicture1.setPreferredSize(new Dimension(0, (int)(parentW * scale)));
        this.picResizing = false;
    }//GEN-LAST:event_amcPicture1ComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcPicture amcPicture1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
