package amc.view.share;

import amc.view.manager.UiUtils;

public class menuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuFrame.class.getName());

    public menuFrame() {
        initComponents();
        UiUtils.applyFlatHoverStyle(btnDepartment);
        UiUtils.applyFlatHoverStyle(btnDoctors);
        UiUtils.applyFlatHoverStyle(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        login_menu = new javax.swing.JPanel();
        login_base = new javax.swing.JPanel();
        btnDepartment = new javax.swing.JButton();
        btnDoctors = new javax.swing.JButton();
        login_service = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10000, 100));
        login_menu1 = new javax.swing.JPanel();
        login_base1 = new javax.swing.JPanel();
        btnDepartment1 = new javax.swing.JButton();
        btnDoctors1 = new javax.swing.JButton();
        login_service1 = new javax.swing.JPanel();
        btnLogin1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(10000, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setPreferredSize(new java.awt.Dimension(1000, 60));
        main.setLayout(new java.awt.CardLayout());

        login_menu.setBackground(new java.awt.Color(0, 139, 139));
        login_menu.setPreferredSize(new java.awt.Dimension(800, 50));
        login_menu.setLayout(new javax.swing.BoxLayout(login_menu, javax.swing.BoxLayout.LINE_AXIS));

        login_base.setBackground(new java.awt.Color(255, 255, 255));
        login_base.setForeground(new java.awt.Color(255, 255, 255));
        login_base.setPreferredSize(new java.awt.Dimension(300, 50));
        login_base.setLayout(new java.awt.GridLayout(1, 0));

        btnDepartment.setBackground(new java.awt.Color(0, 139, 139));
        btnDepartment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDepartment.setText("Department");
        btnDepartment.setBorder(null);
        btnDepartment.setOpaque(true);
        btnDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartmentMouseEntered(evt);
            }
        });
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });
        login_base.add(btnDepartment);

        btnDoctors.setBackground(new java.awt.Color(0, 139, 139));
        btnDoctors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoctors.setText("Doctors");
        btnDoctors.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login_base.add(btnDoctors);

        login_menu.add(login_base);

        login_service.setBackground(new java.awt.Color(0, 139, 139));
        login_service.setPreferredSize(new java.awt.Dimension(520, 50));
        login_service.setLayout(new java.awt.GridLayout(1, 0));
        login_menu.add(login_service);

        btnLogin.setBackground(new java.awt.Color(0, 139, 139));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login_menu.add(btnLogin);
        login_menu.add(filler1);

        main.add(login_menu, "card2");

        login_menu1.setBackground(new java.awt.Color(255, 255, 255));
        login_menu1.setPreferredSize(new java.awt.Dimension(800, 50));
        login_menu1.setLayout(new javax.swing.BoxLayout(login_menu1, javax.swing.BoxLayout.LINE_AXIS));

        login_base1.setBackground(new java.awt.Color(255, 255, 255));
        login_base1.setForeground(new java.awt.Color(255, 255, 255));
        login_base1.setPreferredSize(new java.awt.Dimension(300, 50));
        login_base1.setLayout(new java.awt.GridLayout(1, 0));

        btnDepartment1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDepartment1.setText("Department");
        btnDepartment1.setBorder(null);
        btnDepartment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartment1MouseEntered(evt);
            }
        });
        btnDepartment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartment1ActionPerformed(evt);
            }
        });
        login_base1.add(btnDepartment1);

        btnDoctors1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoctors1.setText("Doctors");
        btnDoctors1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login_base1.add(btnDoctors1);

        login_menu1.add(login_base1);

        login_service1.setBackground(new java.awt.Color(255, 255, 255));
        login_service1.setPreferredSize(new java.awt.Dimension(520, 50));
        login_service1.setLayout(new java.awt.GridLayout(1, 0));
        login_menu1.add(login_service1);

        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin1.setText("Login");
        btnLogin1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        login_menu1.add(btnLogin1);
        login_menu1.add(filler2);

        main.add(login_menu1, "card2");

        getContentPane().add(main, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepartmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartmentMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartmentMouseEntered

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartmentActionPerformed

    private void btnDepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartment1ActionPerformed

    private void btnDepartment1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartment1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartment1MouseEntered

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepartment;
    private javax.swing.JButton btnDepartment1;
    private javax.swing.JButton btnDoctors;
    private javax.swing.JButton btnDoctors1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel login_base;
    private javax.swing.JPanel login_base1;
    private javax.swing.JPanel login_menu;
    private javax.swing.JPanel login_menu1;
    private javax.swing.JPanel login_service;
    private javax.swing.JPanel login_service1;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables
}
