package amc.view.share;

import amc.view.Theme;
import java.awt.CardLayout;
import javax.swing.JPanel;

public class MenuPanel extends javax.swing.JPanel {
    private JPanel userBody = null;
    private JPanel userBar  = null;

    /**
     * Creates new form MainPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuBarPanel = new javax.swing.JPanel();
        picHomeLogo = new amc.view.comp.AmcPicture();
        btnDepts = new amc.view.comp.AmcButton();
        btnDocs = new amc.view.comp.AmcButton();
        sepSplitBar = new javax.swing.JSeparator();
        userBarContainer = new javax.swing.JPanel();
        accountPanel = new javax.swing.JPanel();
        btnLogin = new amc.view.comp.AmcButton();
        picAvatar = new amc.view.comp.AmcPicture();
        bodyPanel = new javax.swing.JPanel();
        homePanel = new amc.view.share.HomePanel();
        userBodyContainer = new javax.swing.JPanel();

        setBackground(Theme.C1_BG);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        menuBarPanel.setBackground(Theme.C2_BG);
        menuBarPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {60, 100, 100, 2, 0, 80};
        jPanel1Layout.columnWeights = new double[] {0.0, 0.0, 0.0, 0.0, 1.0, 0.0};
        jPanel1Layout.rowWeights = new double[] {1.0};
        menuBarPanel.setLayout(jPanel1Layout);

        picHomeLogo.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/logo_clover.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuBarPanel.add(picHomeLogo, gridBagConstraints);

        btnDepts.setText("Departments");
        btnDepts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDepts.setMaximumSize(null);
        btnDepts.setMinimumSize(null);
        btnDepts.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuBarPanel.add(btnDepts, gridBagConstraints);

        btnDocs.setText("Doctors");
        btnDocs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDocs.setMaximumSize(null);
        btnDocs.setMinimumSize(null);
        btnDocs.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuBarPanel.add(btnDocs, gridBagConstraints);

        sepSplitBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        menuBarPanel.add(sepSplitBar, gridBagConstraints);

        userBarContainer.setAutoscrolls(true);
        userBarContainer.setOpaque(false);
        userBarContainer.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        menuBarPanel.add(userBarContainer, gridBagConstraints);

        accountPanel.setOpaque(false);
        accountPanel.setLayout(new java.awt.CardLayout());

        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setMaximumSize(null);
        btnLogin.setMinimumSize(null);
        btnLogin.setPreferredSize(null);
        accountPanel.add(btnLogin, "card2");

        picAvatar.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/avatar_doctor.png"))); // NOI18N
        accountPanel.add(picAvatar, "card3");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        menuBarPanel.add(accountPanel, gridBagConstraints);

        add(menuBarPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setLayout(new java.awt.CardLayout());
        bodyPanel.add(homePanel, "Home");

        userBodyContainer.setOpaque(false);
        userBodyContainer.setLayout(new java.awt.BorderLayout());
        bodyPanel.add(userBodyContainer, "User");

        add(bodyPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public HomePanel getHomePage() {
        return this.homePanel;
    }

    public void setUserPage(JPanel body, BarPanel bar) {
        if (this.userBody != null) userBodyContainer.remove(this.userBody);
        if (this.userBar  != null) userBarContainer.remove(this.userBar);
        this.userBody = body;
        this.userBar  = bar;

        if (body == null || bar == null) return;
        System.out.println(body);
        System.out.println(bar);
        userBodyContainer.add(userBody);
        userBarContainer.add(bar);
        this.switch2Home(false);
    }

    public void switch2Home(boolean option) {
        ((CardLayout) bodyPanel.getLayout()).show(bodyPanel, option ? "Home" : "User");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel bodyPanel;
    private amc.view.comp.AmcButton btnDepts;
    private amc.view.comp.AmcButton btnDocs;
    public amc.view.comp.AmcButton btnLogin;
    private amc.view.share.HomePanel homePanel;
    private javax.swing.JPanel menuBarPanel;
    private amc.view.comp.AmcPicture picAvatar;
    private amc.view.comp.AmcPicture picHomeLogo;
    private javax.swing.JSeparator sepSplitBar;
    private javax.swing.JPanel userBarContainer;
    private javax.swing.JPanel userBodyContainer;
    // End of variables declaration//GEN-END:variables
}
