package amc.view.share;

import amc.model.entity.Appointment;
import amc.view.Theme;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

public class ProfileFeedbackComp extends javax.swing.JPanel implements ListCellRenderer<Appointment>{

    /**
     * Creates new form ProfileFeedbackCom
     */
    public ProfileFeedbackComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        amcRoundBox1 = new amc.view.comp.AmcRoundBox();
        lblApptId = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        picDoctor = new amc.view.comp.AmcPicture();
        lblDoctorName = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        txtFeedback = new javax.swing.JTextArea();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        amcRoundBox1.setBackground(Theme.C1_INTER);
        amcRoundBox1.set$borderWidth(0);
        amcRoundBox1.set$cornerRound(15);
        java.awt.GridBagLayout amcRoundBox1Layout = new java.awt.GridBagLayout();
        amcRoundBox1Layout.rowHeights = new int[] {30, 5, 30, 0};
        amcRoundBox1Layout.columnWeights = new double[] {0.5, 0.5};
        amcRoundBox1Layout.rowWeights = new double[] {0.0, 0.0, 0.0, 1.0};
        amcRoundBox1.setLayout(amcRoundBox1Layout);

        lblApptId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblApptId.setForeground(Theme.C1_FG);
        lblApptId.setText("APT-001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        amcRoundBox1.add(lblApptId, gridBagConstraints);

        lblDate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDate.setForeground(Theme.C1_FG);
        lblDate.setText("27 July 2025");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        amcRoundBox1.add(lblDate, gridBagConstraints);

        jSeparator1.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        amcRoundBox1.add(jSeparator1, gridBagConstraints);

        picDoctor.set$image(new javax.swing.ImageIcon(getClass().getResource("/amc/image/role_doctor.png"))); // NOI18N
        picDoctor.setMaximumSize(new java.awt.Dimension(30, 30));
        picDoctor.setMinimumSize(new java.awt.Dimension(30, 30));
        picDoctor.setName(""); // NOI18N
        picDoctor.setPreferredSize(new java.awt.Dimension(31, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        amcRoundBox1.add(picDoctor, gridBagConstraints);

        lblDoctorName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblDoctorName.setText("Doctor Steve");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 45, 0, 0);
        amcRoundBox1.add(lblDoctorName, gridBagConstraints);

        lblDepartment.setForeground(Theme.C1_FG);
        lblDepartment.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        amcRoundBox1.add(lblDepartment, gridBagConstraints);

        txtFeedback.setEditable(false);
        txtFeedback.setBackground(Theme.C1_INTER);
        txtFeedback.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFeedback.setForeground(Theme.C1_FG);
        txtFeedback.setLineWrap(true);
        txtFeedback.setRows(1);
        txtFeedback.setText("Something here to\nSHOW!!");
        txtFeedback.setWrapStyleWord(true);
        txtFeedback.setBorder(null);
        txtFeedback.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        amcRoundBox1.add(txtFeedback, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(amcRoundBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private amc.view.comp.AmcRoundBox amcRoundBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblApptId;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDoctorName;
    private amc.view.comp.AmcPicture picDoctor;
    private javax.swing.JTextArea txtFeedback;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(
        JList<? extends Appointment> list,
        Appointment value, int index,
        boolean isSelected, boolean cellHasFocus
    ) {
        lblApptId.setText(value.getId());
        lblDate.setText(DateTimeFormatter.ofPattern("dd MMM yyyy").format(value.getDateTime()));
        lblDoctorName.setText(value.getDoctor().getUserName());
        lblDepartment.setText(value.getDepartment().getDepartmentName());
        txtFeedback.setText(value.getFeedback());
        return this;
    }
}
